### ISSUE TITLE
does node support template string?

### ISSUE THREAD

**Issue by cola-sk** [trusktr/regexr#1]
the lastest node version 0.12.5, it does not support template string, but how does the regexr work?

**Comment by trusktr** [comment]
Hello @SKing7, Sorry for the late reply. You have to run this either in a version of Node that supports template strings (possibly with a command line flag) or use this in an environment where code gets transpiled from ES6 to ES5 (for example Webpack or Browserify with Babel).

You'll be happy to know that [current versions of Node.js ship with template-string support.](https://nodejs.org/en/docs/es6/)
