### ISSUE TITLE
http://regexr.com/

### ISSUE THREAD

**Issue by tomByrer** [trusktr/regexr#2]
IIRC I found him 2-3 years ago.
Suggestion: perhaps you should just touch base with him if it OK if you use the name.
Either way, I think your repo is handy, so please don't pull a `left-pad`! ;)

**Comment by trusktr** [comment]
Sorry for the late reply. What's a left-pad?

**Comment by trusktr** [comment]
regexr.com owner, please let me know if you want the name.
